name: Notify Microsoft Teams for All Actions

on: 
  push:                # Trigger on code push events
  pull_request:        # Trigger on pull request events
  issues:              # Trigger on issue-related events
  workflow_dispatch:   # Manual workflow runs
  issue_comment:       # Trigger on issue comment events
  pull_request_review: # Trigger on pull request reviews
  pull_request_target: # Trigger on pull request events for forked repositories
  release:             # Trigger on release events
  fork:                # Trigger when repo is forked

jobs:
  setup_push_commits:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    outputs:
      commit_messages: ${{ steps.collect.outputs.commit_messages }}
    steps:
      - id: collect
        run: |
          commit_messages=""
          
          # Save the commit data into a temporary file or variable to avoid subshell
          commits=$(echo '${{ toJson(github.event.commits) }}' | jq -c '.[]')

          # Process each commit one by one
          while read -r commit; do
            commit_id=$(echo $commit | jq -r '.id')
            commit_url=$(echo $commit | jq -r '.url')
            commit_message=$(echo $commit | jq -r '.message')
            commit_messages="$commit_messages<code><a href='$commit_url'>$commit_id</a></code><br>$commit_message<hr>"
          done <<< "$commits"
          
          # Debug: Log the content of commit_messages to see if it contains anything
          echo "Commit messages content:"
          echo "$commit_messages"

          # Write the multi-line output to GITHUB_OUTPUT
          echo "commit_messages<<EOF" >> $GITHUB_OUTPUT
          echo "$commit_messages" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

  notify:
    needs: [setup_push_commits]  # Ensure push commit matrix is set up first
    runs-on: ubuntu-latest
    steps:
      # Notify for issue events
      - name: Microsoft Teams Notification for Issues
        if: ${{ github.event.issue && github.event_name != 'issue_comment' }}
        uses: aliencube/microsoft-teams-actions@v0.8.0
        with:
          webhook_uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          title: "${{ github.actor }} - <a href='${{ github.event.issue.html_url }}'>New Issue</a>"
          summary: "${{ github.actor }} - Issue ${{ github.event.action }}"
          text: |
            ${{ github.event_name }}<br>
            **New Issue**: ${{ github.event.issue.title }}
          theme_color: "bd0f0f"

      # Notify for issue comments
      - name: Microsoft Teams Notification for Issue Comments
        if: ${{ github.event.comment.body }}
        uses: aliencube/microsoft-teams-actions@v0.8.0
        with:
          webhook_uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          title: "${{ github.actor }} - <a href='${{ github.event.comment.html_url }}'>#${{ github.event.issue.number }} New Comment</a>"
          summary: "${{ github.actor }} - Comment ${{ github.event.action }}"
          text: |
            ${{ github.event_name }}<br>
            **New Comment**: ${{ github.event.issue.title }}<br>
            ${{ github.event.comment.body }}
          theme_color: "bd4f0f"

      # Notify for pull request events
      - name: Microsoft Teams Notification for Pull Requests
        if: ${{ github.event.pull_request }}
        uses: aliencube/microsoft-teams-actions@v0.8.0
        with:
          webhook_uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          title: "${{ github.actor }} - <a href='${{ github.event.pull_request.html_url }}'>New Pull Request</a>"
          summary: "${{ github.actor }} - Pull Request ${{ github.event.action }}"
          text: |
            ${{ github.event_name }}<br>
            **Pull Request**: ${{ github.event.pull_request.title }}
          theme_color: "660fbd"

      # Send notification to Microsoft Teams with all commit messages in one webhook
      - name: Microsoft Teams Notification for Push Events
        uses: aliencube/microsoft-teams-actions@v0.8.0
        with:
          webhook_uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          title: "${{ github.actor }} - Pushed Commits"
          summary: "${{ github.actor }} pushed new commits"
          text: "${{ needs.setup_push_commits.outputs.commit_messages }}"
          theme_color: "12bd0f"

      # Notify for release events
      - name: Microsoft Teams Notification for Releases
        if: ${{ github.event.release }}
        uses: aliencube/microsoft-teams-actions@v0.8.0
        with:
          webhook_uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          title: "${{ github.actor }} - <a href='${{ github.event.release.html_url }}'>New Release</a>"
          summary: "${{ github.actor }} - Release ${{ github.event.action }}"
          text: |
            ${{ github.event_name }}<br>
            **New Release**: ${{ github.event.release.name }} - ${{ github.event.release.tag_name }}
          theme_color: "0076D7"

      # Notify for fork events
      - name: Microsoft Teams Notification for Fork Events
        if: ${{ github.event_name == 'fork' }}
        uses: aliencube/microsoft-teams-actions@v0.8.0
        with:
          webhook_uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          title: "${{ github.actor }} - New Fork"
          summary: "${{ github.actor }} - Fork ${{ github.event.action }}"
          text: |
            ${{ github.event_name }}<br>
            **Repository Forked**: ${{ github.repository.full_name }} was forked by <a href='${{ github.actor.html_url }}'>${{ github.actor }}</a>
          theme_color: "0fbd80"

      # Default notification for any other actions not covered
      - name: Microsoft Teams Default Notification
        if: ${{ github.event_name != 'push' && github.event_name != 'pull_request' && github.event_name != 'issues' && github.event_name != 'release' && github.event_name != 'fork' && github.event_name != 'issue_comment' }}
        uses: aliencube/microsoft-teams-actions@v0.8.0
        with:
          webhook_uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          title: "${{ github.actor }} - ${{ github.event_name }} Unregistered Event"
          summary: "${{ github.actor }} - ${{ github.event_name }} ${{ github.event.action }}"
          text: |
            ${{ github.event_name }}<br>
            **Action Details**: Event: ${{ github.event_name }}, Action: ${{ github.event.action }}"
          theme_color: "ec05fc"
