name: Notify Microsoft Teams for All Actions

on: 
  push:                # Trigger on code push events
  pull_request:        # Trigger on pull request events
  issues:              # Trigger on issue-related events
  workflow_dispatch:   # Manual workflow runs
  issue_comment:       # Trigger on issue comment events
  pull_request_review: # Trigger on pull request reviews
  pull_request_target: # Trigger on pull request events for forked repositories
  release:             # Trigger on release events
  fork:                # Trigger when repo is forked

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      # Notify for issue events
      - name: Microsoft Teams Notification for Issues
        if: ${{ github.event.issue }}
        uses: aliencube/microsoft-teams-actions@v0.8.0
        with:
          webhook_uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          title: "${{ github.actor }} - Issue Event"
          summary: "${{ github.actor }} - Issue ${{
            github.event.action }}"
          text: |
            **New Issue**: ${{ github.event.issue.title }}
          theme_color: "0076D7"

      # Notify for pull request events
      - name: Microsoft Teams Notification for Pull Requests
        if: ${{ github.event.pull_request }}
        uses: aliencube/microsoft-teams-actions@v0.8.0
        with:
          webhook_uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          title: "${{ github.actor }} - Pull Request Event"
          summary: "${{ github.actor }} - Pull Request ${{
            github.event.action }}"
          text: |
            **Pull Request**: ${{ github.event.pull_request.title }}
          theme_color: "0076D7"

      # Notify for push events (commits)
      - name: Microsoft Teams Notification for Push Events
        if: ${{ github.event_name == 'push' }}
        uses: aliencube/microsoft-teams-actions@v0.8.0
        with:
          webhook_uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          title: "${{ github.actor }} - Push Event"
          summary: "${{ github.actor }} pushed commits"
          text: |
            **Commit Message**: ${{ github.event.commits[0].message }}
          theme_color: "0076D7"

      # Notify for issue comments
      - name: Microsoft Teams Notification for Issue Comments
        if: ${{ github.event.issue_comment }}
        uses: aliencube/microsoft-teams-actions@v0.8.0
        with:
          webhook_uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          title: "${{ github.actor }} - Comment Event"
          summary: "${{ github.actor }} - Comment ${{
            github.event.action }}"
          text: |
            **New Comment**: ${{ github.event.comment.body }}
          theme_color: "0076D7"

      # Notify for release events
      - name: Microsoft Teams Notification for Releases
        if: ${{ github.event.release }}
        uses: aliencube/microsoft-teams-actions@v0.8.0
        with:
          webhook_uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          title: "${{ github.actor }} - Release Event"
          summary: "${{ github.actor }} - Release ${{
            github.event.action }}"
          text: |
            **New Release**: ${{ github.event.release.name }} - ${{ github.event.release.tag_name }}
          theme_color: "0076D7"

      # Notify for fork events
      - name: Microsoft Teams Notification for Fork Events
        if: ${{ github.event_name == 'fork' }}
        uses: aliencube/microsoft-teams-actions@v0.8.0
        with:
          webhook_uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          title: "${{ github.actor }} - Fork Event"
          summary: "${{ github.actor }} - Fork ${{
            github.event.action }}"
          text: |
            **Repository Forked**: ${{ github.repository.full_name }} was forked by ${{ github.actor }}
          theme_color: "0076D7"

      # Default notification for any other actions not covered
      - name: Microsoft Teams Default Notification
        if: ${{ github.event_name != 'push' && github.event_name != 'pull_request' && github.event_name != 'issues' && github.event_name != 'release' && github.event_name != 'fork' && github.event_name != 'issue_comment' }}
        uses: aliencube/microsoft-teams-actions@v0.8.0
        with:
          webhook_uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          title: "${{ github.actor }} - ${{
            github.event_name }} Event"
          summary: "${{ github.actor }} - ${{
            github.event_name }} ${{
            github.event.action }}"
          text: |
            **Action Details**: Event: ${{ github.event_name }}, Action: ${{ github.event.action }}
          theme_color: "0076D7"
