name: Notify Microsoft Teams for All Actions

on: 
  push:                # Trigger on code push events
  pull_request:        # Trigger on pull request events
  issues:              # Trigger on issue-related events
  workflow_dispatch:   # Manual workflow runs
  issue_comment:       # Trigger on issue comment events
  pull_request_review: # Trigger on pull request reviews
  pull_request_target: # Trigger on pull request events for forked repositories
  release:             # Trigger on release events
  fork:                # Trigger when repo is forked

jobs:
  setup_push_commits:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.commit_data }}
    steps:
      # Collect commit IDs, URLs, and messages as a matrix
      - id: matrix
        run: |
          # Collect commit data in JSON format
          commits=$(jq -n --argjson commits "${{ toJson(github.event.commits) }}" \
            '$commits | map({id: .id, message: .message, url: .url})')

          # Output commit data
          echo "commit_data=$commits" >> $GITHUB_OUTPUT
      - run: |
          echo "Commit Data: ${{ steps.matrix.outputs.commit_data }}"

  notify:
    needs: [setup_push_commits]  # Ensure push commit matrix is set up first
    runs-on: ubuntu-latest
    strategy:
      matrix:
        commit: ${{ fromJSON(needs.setup_push_commits.outputs.matrix) }}
    steps:
      # Notify for issue events
      - name: Microsoft Teams Notification for Issues
        if: ${{ github.event.issue && github.event_name != 'issue_comment' }}
        uses: aliencube/microsoft-teams-actions@v0.8.0
        with:
          webhook_uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          title: "${{ github.actor }} - <a href='${{ github.event.issue.html_url }}'>New Issue</a>"
          summary: "${{ github.actor }} - Issue ${{ github.event.action }}"
          text: |
            ${{ github.event_name }}<br>
            **New Issue**: ${{ github.event.issue.title }}
          theme_color: "bd0f0f"

      # Notify for issue comments
      - name: Microsoft Teams Notification for Issue Comments
        if: ${{ github.event.comment.body }}
        uses: aliencube/microsoft-teams-actions@v0.8.0
        with:
          webhook_uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          title: "${{ github.actor }} - <a href='${{ github.event.comment.html_url }}'>#${{ github.event.issue.number }} New Comment</a>"
          summary: "${{ github.actor }} - Comment ${{ github.event.action }}"
          text: |
            ${{ github.event_name }}<br>
            **New Comment**: ${{ github.event.issue.title }}<br>
            ${{ github.event.comment.body }}
          theme_color: "bd4f0f"

      # Notify for pull request events
      - name: Microsoft Teams Notification for Pull Requests
        if: ${{ github.event.pull_request }}
        uses: aliencube/microsoft-teams-actions@v0.8.0
        with:
          webhook_uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          title: "${{ github.actor }} - <a href='${{ github.event.pull_request.html_url }}'>New Pull Request</a>"
          summary: "${{ github.actor }} - Pull Request ${{ github.event.action }}"
          text: |
            ${{ github.event_name }}<br>
            **Pull Request**: ${{ github.event.pull_request.title }}
          theme_color: "660fbd"

      # Send notification to Microsoft Teams for push events with all commit messages
      - name: Microsoft Teams Notification for Push Events
        uses: aliencube/microsoft-teams-actions@v0.8.0
        with:
          webhook_uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          title: "${{ github.actor }} - Pushed Commit"
          summary: "${{ github.actor }} pushed a new commit"
          text: |
            **Commit:** <code><a href="${{ matrix.commit.url }}">{{ matrix.commit.id }}</a></code><br>
            **Message:**<br>
            ${{ matrix.commit.message }}<hr>
          theme_color: "12bd0f"

      # Notify for release events
      - name: Microsoft Teams Notification for Releases
        if: ${{ github.event.release }}
        uses: aliencube/microsoft-teams-actions@v0.8.0
        with:
          webhook_uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          title: "${{ github.actor }} - <a href='${{ github.event.release.html_url }}'>New Release</a>"
          summary: "${{ github.actor }} - Release ${{ github.event.action }}"
          text: |
            ${{ github.event_name }}<br>
            **New Release**: ${{ github.event.release.name }} - ${{ github.event.release.tag_name }}
          theme_color: "0076D7"

      # Notify for fork events
      - name: Microsoft Teams Notification for Fork Events
        if: ${{ github.event_name == 'fork' }}
        uses: aliencube/microsoft-teams-actions@v0.8.0
        with:
          webhook_uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          title: "${{ github.actor }} - New Fork"
          summary: "${{ github.actor }} - Fork ${{ github.event.action }}"
          text: |
            ${{ github.event_name }}<br>
            **Repository Forked**: ${{ github.repository.full_name }} was forked by <a href='${{ github.actor.html_url }}'>${{ github.actor }}</a>
          theme_color: "0fbd80"

      # Default notification for any other actions not covered
      - name: Microsoft Teams Default Notification
        if: ${{ github.event_name != 'push' && github.event_name != 'pull_request' && github.event_name != 'issues' && github.event_name != 'release' && github.event_name != 'fork' && github.event_name != 'issue_comment' }}
        uses: aliencube/microsoft-teams-actions@v0.8.0
        with:
          webhook_uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          title: "${{ github.actor }} - ${{ github.event_name }} Unregistered Event"
          summary: "${{ github.actor }} - ${{ github.event_name }} ${{ github.event.action }}"
          text: |
            ${{ github.event_name }}<br>
            **Action Details**: Event: ${{ github.event_name }}, Action: ${{ github.event.action }}"
          theme_color: "ec05fc"
