name: Notify Microsoft Teams for All Actions

on: 
  push:     # Trigger on code push events
  pull_request:    # Trigger on pull request events
  issues:   # Trigger on issue-related events
  workflow_run:    # Trigger on workflow runs
  workflow_dispatch:  # Manual runs
  issue_comment:  # Trigger on issue comment events
  pull_request_review: # Trigger on pull request reviews
  pull_request_target:
  release:  # Trigger on release events
  fork: # Trigger when repo is forked

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Microsoft Teams (Generic)
        uses: aliencube/microsoft-teams-actions@v0.8.0
        with:
          webhook_uri: ${{ secrets.TEAMS_WEBHOOK_URI }}
          title: "GitHub Action Event"
          summary: "A GitHub event has occurred."
          text: "This is a notification for a GitHub action event in the repository."
          theme_color: "0076D7"  # Optional: Customize with a hexadecimal color
