name: Notify Microsoft Teams for All Actions

on: 
  push:                # Trigger on code push events
  pull_request:        # Trigger on pull request events
  issues:              # Trigger on issue-related events
  workflow_dispatch:   # Manual workflow runs
  issue_comment:       # Trigger on issue comment events
  pull_request_review: # Trigger on pull request reviews
  pull_request_target: # Trigger on pull request events for forked repositories
  release:             # Trigger on release events
  fork:                # Trigger when repo is forked

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Microsoft Teams (Generic)
        uses: aliencube/microsoft-teams-actions@v0.8.0
        with:
          webhook_uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          title: "${{ github.actor }} - ${{ github.event_name }}"
          summary: "${{ github.actor }} - ${{ github.event.action }}"
          text: |
            ${{ github.event.issue ? '**New Issue**: [' + github.event.issue.title + '](' + github.event.issue.html_url + ')' 
            : github.event.pull_request ? '**Pull Request**: [' + github.event.pull_request.title + '](' + github.event.pull_request.html_url + ')' 
            : github.event.commits ? '**Commit**: [' + github.event.commits[0].message + '](' + github.event.repository.html_url + '/commit/' + github.event.commits[0].id + ')' 
            : github.event.comment ? '**New Comment**: [Comment by ' + github.actor + '](' + github.event.comment.html_url + ') on issue/pull request' 
            : github.event.release ? '**New Release**: [' + github.event.release.name + '](' + github.event.release.html_url + ') - ' + github.event.release.tag_name 
            : github.event.fork ? '**Repository Forked**: [' + github.repository.full_name + '](' + github.repository.html_url + ') was forked by ' + github.actor 
            : '**Action Details**: Event: ' + github.event_name + ', Action: ' + github.event.action }}
          theme_color: "0076D7"  # Optional: Customize with a hexadecimal color
