name: Notify Microsoft Teams for All Actions

on: 
  push:                # Trigger on code push events
  pull_request:        # Trigger on pull request events
  issues:              # Trigger on issue-related events
  workflow_dispatch:   # Manual workflow runs
  issue_comment:       # Trigger on issue comment events
  pull_request_review: # Trigger on pull request reviews
  pull_request_target: # Trigger on pull request events for forked repositories
  release:             # Trigger on release events
  fork:                # Trigger when repo is forked

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Microsoft Teams (Generic)
        uses: aliencube/microsoft-teams-actions@v0.8.0
        with:
          webhook_uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          title: "${{ github.event_name }}"
          summary: "${{ github.actor }} - ${{ github.event.action }}"
          text: |
            **Action Type**: ${{ github.event_name }} 
            **Action Details**: ${{ github.event.action }} - ${{ github.event.issue.title || github.event.pull_request.title || github.event.commits[0].message }} 
            **By**: ${{ github.actor }}
          theme_color: "0076D7"  # Optional: Customize with a hexadecimal color
